### PR TITLE
fixed redundant geocoder attribution problem

### LINKED ISSUE #384: redundant attribution for geocoding
After starting bundling geocoder, mapzen.js shows the attribution for geocoding, which is redundant. 
screen shot 2017-05-07 at 5 51 26 am

### PR DESCRIPTION
**Pull request by hanbyul-here**
- closes #384

### CODE REVIEW

File: src/js/components/search.js [hunk 1]
```diff
@@ -3,20 +3,28 @@ var APIKeyCheck = require('./apiKeyCheck');
...
     // When nothing is passed
     apiKey = L.Mapzen.apiKey;
-  } else if (typeof key === 'object') {
+
+  } else if (typeof _key === 'object') {
     // When the key is omitted and options is passed
     apiKey = L.Mapzen.apiKey;
-    options = key;
+    options = _key;
+    if (_options.attribution) attribution += _options.attribution;
```
Comment (rfriberg) [inline src/js/components/search.js]: What is this line for?  Are you expecting that users will pass a second set of options containing `attribution`?

Comment (hanbyul-here) [inline src/js/components/search.js]: yeah that is what I assumed since Leaflet-geocoder has attribution option and mapzen.js shares the docs with it. More I think, it would be better to guide people to use attribution options for map control. I will still leave it here just in case, but let's not promote this.
